test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>


  # Reference to development.rb
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


cloudinary:
  service: Cloudinary
  folder: <%= Rails.env %>